general:
  data_path: ../Data/
  model_name: digit82/kobart-summarization
  output_dir: ./
inference:
  batch_size: 32
  ckt_path: model ckt path
  early_stopping: true
  generate_max_length: 50 # 변경: 요약문 길이 커버
  no_repeat_ngram_size: 2
  num_beams: 5 # 변경: Abstractive 특성을 반영하여 탐색 공간 확장
  remove_tokens:
  - <usr>
  - <s>
  - </s>
  - <pad>
  result_path: ./prediction/
tokenizer:
  bos_token: <s>
  decoder_max_len: 50 # 변경
  encoder_max_len: 1024 # 변경: 95% 커버리지를 위한 확장
  eos_token: </s>
  special_tokens: # 변경: 22개 특수 토큰 완벽 반영
  - "#Person1#"
  - "#Person2#"
  - "#Person3#"
  - "#Person4#"
  - "#Person5#"
  - "#Person6#"
  - "#Person7#"
  - '#CardNumber#'
  - '#Address#'
  - '#Alex#'
  - '#CarNumber#'
  - '#Price#'
  - '#Liliana#'
  - '#PhoneNumber#'
  - '#PassportNumber#'
  - '#DateOfBirth#'
  - '#PersonName#'
  - '#Email#'
  - '#Kristin#'
  - '#Name#'
  - '#SSN#'
  - '#Bob#'
training:
  do_eval: true
  do_train: true
  early_stopping_patience: 3
  early_stopping_threshold: 0.001
  evaluation_strategy: epoch
  fp16: true
  generation_max_length: 50 # 변경
  gradient_accumulation_steps: 1
  learning_rate: 1.0e-05
  load_best_model_at_end: true
  logging_dir: ./logs
  logging_strategy: epoch
  lr_scheduler_type: cosine
  num_train_epochs: 5
  optim: adamw_torch
  overwrite_output_dir: true
  per_device_eval_batch_size: 16
  per_device_train_batch_size: 16 # 변경: OOM 방지를 위한 배치 사이즈 축소
  predict_with_generate: true
  report_to: wandb
  save_strategy: epoch
  save_total_limit: 5
  seed: 42
  warmup_ratio: 0.1
  weight_decay: 0.01
wandb:
  entity:  # 주의: 본인의 wandb 아이디로 변경!
  name: kobart_abstractive_run
  project: NLPProject